# Generated by Django 3.1.3 on 2023-08-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='enrollment',
            new_name='enrollment_id',
        ),
    ]
