# Generated by Django 3.1.3 on 2023-08-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230817_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission_choices',
            name='choice_id',
        ),
        migrations.AddField(
            model_name='submission_choices',
            name='choice_id',
            field=models.ManyToManyField(to='onlinecourse.Choice'),
        ),
    ]
